version: '3.8'

services:
    frontend:
        build: .
        container_name: jfd-to-do-list-react
        ports:
            - '8088:80'
        depends_on:
            - json-server

    json-server:
        build:
            context: .
            dockerfile: Dockerfile.json-server
        container_name: json-server
        ports:
            - '8089:3000'
